### ISSUE TITLE
2주차 세미나 기본/심화 과제

### ISSUE THREAD

**Issue by 2zerozu** [GO-SOPT-SERVER/LeeYeongJu#5]
## 📌 Feature Issue

2주차 세미나 기본/심화 과제

## 📝 To-do

- [ ] 기본 : 실습코드 Github에 올리기
- [ ] 심화 : GET, POST, PUT, DELETE Method를 각각 사용하는 API 만들기
- [ ] 심화 : 본인이 만든 API 명세서 작성하기 → 템플릿 사용 금지 (본인이 만들 것)
