### ISSUE TITLE
3주차 세미나 기본/심화 과제

### ISSUE THREAD

**Issue by 2zerozu** [GO-SOPT-SERVER/LeeYeongJu#6]
## 📌 Feature Issue

3주차 세미나 기본/심화 과제

## 📝 To-do

- [ ] 기본 : 실습코드 Github에 올리기
- [ ] 심화 : user테이블과 post테이블을 각각 만들고 테이블의 연관관계 만들기 (FK)
- [ ] 심화 : 유저 생성, 게시물 생성, 게시물 조회 구현
- [ ] 심화 : 각각 API에 맞는 예외 처리 구현
